server:
  port: 8332

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://192.168.43.200:3306/test_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 172.17.0.2
    port: 6379
    password:
    timeout: 1000

mybatis:
  type-aliases-package: com.liupanlong.test2.pojo
  mapper-locations: classpath:mapper/*Mapper.xml      #mapper映射文件路径

logging:
  file:
    name: log/log.log
  level:
    root: info
    test2: debug
